### ISSUE TITLE
Key Error: 20

### ISSUE THREAD

**Issue by amolsharma99** [JosPolfliet/pandas-profiling#13]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-145-9a2bae14ffa8> in <module>()
----> 1 profile = pandas_profiling.ProfileReport(selectFeatureData)
      2 profile.to_file(outputfile="allData.html")

/home/amol/anaconda/lib/python2.7/site-packages/pandas_profiling/__init__.pyc in __init__(self, df)
     15         description_set = describe(df)
     16         self.html = to_html(df.head(),
---> 17                             description_set)
     18 
     19     def to_file(self, outputfile=DEFAULT_OUTPUTFILE):

/home/amol/anaconda/lib/python2.7/site-packages/pandas_profiling/base.pyc in to_html(sample_df, stats_object)
    313                                                            templates.mini_freq_table, templates.mini_freq_table_row, 3)
    314             formatted_values['freqtable'] = freq_table(stats_object['freq'][idx], n_obs,
--> 315                                                        templates.freq_table, templates.freq_table_row, 20)
    316             if row['distinct_count'] > 50:
    317                 messages.append(templates.messages['HIGH_CARDINALITY'].format(formatted_values, varname = formatters.fmt_varname(idx)))

/home/amol/anaconda/lib/python2.7/site-packages/pandas_profiling/base.pyc in freq_table(freqtable, n, table_template, row_template, max_number_of_items_in_table)
    252         freq_rows_html = u''
    253 
--> 254         freq_other = sum(freqtable[max_number_of_items_in_table:])
    255         freq_missing = n - sum(freqtable)
    256         max_freq = max(freqtable.values[0], freq_other, freq_missing)

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    595             key = check_bool_indexer(self.index, key)
    596 
--> 597         return self._get_with(key)
    598 
    599     def _get_with(self, key):

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/series.pyc in _get_with(self, key)
    600         # other: fancy integer or otherwise
    601         if isinstance(key, slice):
--> 602             indexer = self.index._convert_slice_indexer(key, kind='getitem')
    603             return self._get_values(indexer)
    604         elif isinstance(key, ABCDataFrame):

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/index.pyc in _convert_slice_indexer(self, key, kind)
   3871 
   3872         # translate to locations
-> 3873         return self.slice_indexer(key.start, key.stop, key.step)
   3874 
   3875     def get_value(self, series, key):

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/index.pyc in slice_indexer(self, start, end, step, kind)
   2568         This function assumes that the data is sorted, so use at your own peril
   2569         """
-> 2570         start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
   2571 
   2572         # return a slice

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/index.pyc in slice_locs(self, start, end, step, kind)
   2712         start_slice = None
   2713         if start is not None:
-> 2714             start_slice = self.get_slice_bound(start, 'left', kind)
   2715         if start_slice is None:
   2716             start_slice = 0

/home/amol/anaconda/lib/python2.7/site-packages/pandas/core/index.pyc in get_slice_bound(self, label, side, kind)
   2660             except ValueError:
   2661                 # raise the original KeyError
-> 2662                 raise err
   2663 
   2664         if isinstance(slc, np.ndarray):

KeyError: 20.0

**Comment by JosPolfliet** [comment]
Hi, thanks for reporting. Can you share the DataFrame that generated this error? You can e-mail me on my personal e-mail address if you don't want to make it public.

Any reproducible example would be fine too.

Thanks
