### ISSUE TITLE
When processing large data files about 800MB errors out

### ISSUE THREAD

**Issue by ranam008** [JosPolfliet/pandas-profiling#14]
Thank you so much for this great program which helps me a lot, but When I try to process a file of 800mb it errors out saying memory error how to process this huge files. Please guide me in this.

**Comment by jc-healy** [comment]
Hi Ranam,

Are you trying to compute the full distance matrix?  That would certainly
cause you to run out of memory on a large file.  What distance function are
you using?

Cheers
John

**Comment by ranam008** [comment]
thank you john for your reply, I am not sure what you meant can you please elaborate a little more.

**Comment by JosPolfliet** [comment]
Right now, there is no easy way to to chunked calculations. It would be a great addition but would require a lot of re-engineering.

I'm going to close this since there is no easy fix (besides upgrading your memory capacity or buying a commercial package)
