### ISSUE TITLE
Error while running- AttributeError: 'Series' object has no attribute 'memory_usage'

### ISSUE THREAD

**Issue by amolsharma99** [JosPolfliet/pandas-profiling#2]
I have this dataset, all values are numerical (int/float).
![df2](https://cloud.githubusercontent.com/assets/1535233/12703327/7101c00c-c866-11e5-9bfa-152d91edc701.png)

Not Sure why i am getting this error.
![df1](https://cloud.githubusercontent.com/assets/1535233/12703329/794d5e9c-c866-11e5-82ce-945de836cee5.png)

pandas version - 0.17.0
matplotlib version - 1.5.0

**Comment by JosPolfliet** [comment]
I have noticed this bug too when using pandas 0.16.x, but 0.17 should not have been affected. I thought I fixed it a couple of days ago. Can you try upgrading to the latest version (pip install -U pandas-profiling) and let me know if it is still there?

**Comment by amolsharma99** [comment]
Upgrading fixed it. Thanks :)
