### ISSUE TITLE
Profiling one variable

### ISSUE THREAD

**Issue by bourbe** [JosPolfliet/pandas-profiling#24]
Hi,
  very great job !!!!!!!  I have a problem

I tried to profile just one variable by using this 

```sh
pandas_profiling.ProfileReport(pd.DataFrame(training['num_var4'], columns=['num_var4']))
```

The problem is in the toggle details, I just have the Statistics but not the Histogram, Common Values, Extreme Values.

How to have them? 

Your package is very great !

regards

**Comment by JosPolfliet** [comment]
Which version of pandas-profiling are you using? That functionality is only available from version 1.3.0 onwards. You can check in a terminal by running `pip freeze | grep pandas-profiling`.

**Comment by bourbe** [comment]
Hi,

  I downloaded the files here in github : https://github.com/JosPolfliet/pandas-profiling
 So I have the file in local and i cannot do '''sh pip freeze | grep pandas-profiling '''

 My version is the one kon github

thanks

**Comment by JosPolfliet** [comment]
What is the detected variable type of your variable? Can you check with diff if the numeric rows template (https://github.com/JosPolfliet/pandas-profiling/blob/master/pandas_profiling/templates/row_num.html) is the same as your local file? 

If the detected variable type is Numeric, and the template is the same, can you share your data so I can see if I can replicate the data? A replicating sample of the data, or fake data, is fine too.

**Comment by JosPolfliet** [comment]
Closing since no response for 2 weeks.
