### ISSUE TITLE
HDFStore chunksize

### ISSUE THREAD

**Issue by cowden** [JosPolfliet/pandas-profiling#26]
Is it possible to profile a large dataset in HDF5 file store by iterating over chunks?  Something perhaps like the following:

pandas_profiling.ProfileReport(store.select('table',chunksize=10000))

Thanks,
C

**Comment by JosPolfliet** [comment]
Hi,

It is not. All the calculations are done in pandas, so if pandas gets support for calculating basic statistics and frequencies in chunks, or via HDF5 connectors, it would be very easy to adapt to pandas-profiling.

For now, your best bet would be to:

- Rewrite the backend of pandas-profiling to use Spark, Hive or another technology that can calculate summary statistics using hadoop
- Use a commercial solution like SAS Data Loader for Hadoop [http://www.sas.com/en_us/software/data-management/data-loader-hadoop.html](http://www.sas.com/en_us/software/data-management/data-loader-hadoop.html) 

Jos

**Comment by cowden** [comment]
Thanks.  Great tool by the way.
