### ISSUE TITLE
memory & CPU eating

### ISSUE THREAD

**Issue by ohld** [JosPolfliet/pandas-profiling#30]
Then I try to generate several _pandas_profilings_ for big tables it generates a lot of processes. Perhaps some of the threads are not closing properly. And become zombie processes and eating CPU and RAM. 
Python 2, Ubuntu 14.04, Jupyter Notebook 4.

**Comment by JosPolfliet** [comment]
Have you tried using the `pool_size` keyword argument in the `describe` function? If you put that to 1, only 1 thread should be used. By default, there is one worker thread for every cpu.

Relevant code: 

```
def describe(df, bins=10, correlation_overrides=None, pool_size=multiprocessing.cpu_count(), **kwargs):
pool = multiprocessing.Pool(pool_size)
```
