### ISSUE TITLE
Adding plots for dates attribuets

### ISSUE THREAD

**Issue by eyaltrabelsi** [JosPolfliet/pandas-profiling#31]
Man what you have done with pandas-profiling is amazing it saves me hours a week !!
I think it would be great to have an additional plot for date attributes .

thx

**Comment by JosPolfliet** [comment]
There already is a histogram for dates in the newest version. What additional plot would you like to see?

**Comment by eyaltrabelsi** [comment]
I was on old version of the package , sorry
