### ISSUE TITLE
Duplicated functions?

### ISSUE THREAD

**Issue by dpavlic** [JosPolfliet/pandas-profiling#37]
Hi Jos,

It seems to me there are (almost) duplicated functions in `base.py` with `describe` having inner functions that are almost identical to the outer functions. I've chopped those off, as seen here:

https://github.com/dpavlic/pandas-profiling/commit/20df9e64b2e1b4c79999339ee0d0f81621ec0037

The tests all run and everything still generates as usual. Am I missing something, or can these go?

**Comment by tejaslodaya** [comment]
IMO, these can go, for now. Because, the `multiprocess_func` calls `describe_1d` which is an outer function.
I think Jos wanted to build a seperate module for those describe_* functions, and didn't want any dependency on the core `describe` function.

**Comment by tejaslodaya** [comment]
@dpavlic Why don't you issue a PR, and merge them. It sounds relevant for now.
CC: @JosPolfliet

**Comment by JosPolfliet** [comment]
Thanks guys, I will take a look soon. Finishing up some other project and then this one has my primary attention again. Hopefully next week I will have some free hours to check this out.
