### ISSUE TITLE
Clashing text with very long variable names

### ISSUE THREAD

**Issue by dpavlic** [JosPolfliet/pandas-profiling#39]
Long variable names seem to cause a bit of a problem as seen here:

![overfill](https://cloud.githubusercontent.com/assets/1075079/22222330/6ac496fa-e184-11e6-92ee-44e431db2198.png)

I am by no means very familiar with bootstrap, but it would seem to me that making the variable take the full grid, and then offsetting the actual stats rows would do the trick:

https://github.com/JosPolfliet/pandas-profiling/compare/master...dpavlic:fix_longname

This would mean the variable names would sit on its own with the relevant stats underneath, like so:

![text-alone](https://cloud.githubusercontent.com/assets/1075079/22222351/82300662-e184-11e6-9757-d87113ca2816.png)

**Comment by JosPolfliet** [comment]
I personally find that always starting a new line introduces a lot of extra and usually unnecessary whitespace. I changed the overflow-x css setting instead, allowing for a scrollbar to appear only if it is strictly necessary. Not the cleanest solution either, but I do think that varnames over 30 character without spaces are more exception than rule. See https://github.com/JosPolfliet/pandas-profiling/commit/b790b33d9aae03146bf55d790c3b10f2fe468b92

Example: 
![image](https://cloud.githubusercontent.com/assets/12380065/22567936/1e7b4aa8-e992-11e6-9d24-d6d01262ca74.png)

Thanks for catching this! Hope you're happy with this solution too!
