### ISSUE TITLE
Enhancement: add binary variable type

### ISSUE THREAD

**Issue by JosPolfliet** [JosPolfliet/pandas-profiling#44]
If the number of distinct values of a numerical value is 2, the current report is overkill, and even confusing. A simpler layout would be better.

**Comment by tejaslodaya** [comment]
You mean to say, the project should have 3 variable types:
1. Numerical 
2. Categorical
3. Binary?

Let me know if you meant something else

**Comment by JosPolfliet** [comment]
@tejaslodaya I think adding a new template is enough. Right now there are already 7 different template types:
```
'NUM'
'DATE'
'DISCRETE'
'CAT'
'UNIQUE'
'CONST'
'CORR'
'RECODED'
```
Skipping some calculations that are not needed for numeric variables with only 2 distinct values would be good for performance of course.

**Comment by romainx** [comment]
Hello,

A new boolean type has been added (see #25). However currently only `bool` columns are treated as boolean. I will extend this behavior to also take into account other type of variables with exactly two distinct values. This will be treated has an option since this behavior could not be always wanted.

Regards

**Comment by conradoqg** [comment]
Hey,

With the above PR #86 merged:

- The profiler now treats numeric types that have 2 distinct values as a boolean "0/1";

We can a create a specific feature request to deal with categorical fields with 2 distinct values and 3 distinct values like "Y/N/NaN".

I think we can close this issue after those changes.

Best

**Comment by romainx** [comment]
Good I close this issue and created one specific to extend the binary type -> #85.
