### ISSUE TITLE
AttributeError: 'module' object has no attribute 'api'

### ISSUE THREAD

**Issue by LEO-E-100** [JosPolfliet/pandas-profiling#46]
On running `import pandas_profiling` and then `pandas_profiling.ProfileReport(df)`

An AttributeError is returned as shown:
<img width="1103" alt="pandas-profiling error image" src="https://cloud.githubusercontent.com/assets/13384374/26512596/2ffbebfe-425f-11e7-9063-c4e6a04bb25e.png">

I have tried my best to understand this error but it doesn't make any sense to me. I have installed as recommended on README and have followed the standard debugging steps but can't get this to work.

Any help would be greatly appreciated!

**Comment by tejaslodaya** [comment]
This is not Pandas profiling error. 

Please update your python to 3.5 and above, since the version you are using has multiprocessing bug. 

You can use virtualenv if you don't want to mess up with the root installation. 

Update here if it works.

**Comment by tejaslodaya** [comment]
Any update? @LEO-E-100

**Comment by LEO-E-100** [comment]
Sorry for the late reply, I have been travelling with limited internet. My virtualenv was not up to 3.5 so this fixed the issue. Many thanks for the prompt response and apologies for the slow reply.

**Comment by tejaslodaya** [comment]
Glad I could help.
And, thanks for closing the issue.
