### ISSUE TITLE
AttributeError: module 'pandas_profiling' has no attribute 'formatters'

### ISSUE THREAD

**Issue by ResidentMario** [JosPolfliet/pandas-profiling#5]
Not sure what's up with that.

![screen shot 2016-03-18 at 3 31 48 pm](https://cloud.githubusercontent.com/assets/3466341/13889740/966f69f2-ed1e-11e5-9e99-943254ece452.png)

**Comment by JosPolfliet** [comment]
Hmm that shouldn't happen. How did you install pandas-profiling: from source or using pip? Can you check if the folder /Users/Honors/anaconda/envs/motor-vehicle-collosions/lib/python3.5/site-packages/pandas_profiling/ contains a file called formatters.py?

**Comment by ResidentMario** [comment]
It's `pip` installed and `formatters.py` is, indeed, there. Smells like a strange environmental error perhaps?

**Comment by ResidentMario** [comment]
Edit: seems to be a technical hiccup on the Python side. After recreating the environment everything runs fine.

This project is beautiful by the way! :+1:

**Comment by ngupta23** [comment]
@ResidentMario Could you provide specific instructions on how you recreated the environment. I am having the same issue.

**Comment by ResidentMario** [comment]
No idea really what I did at this point because it was so long ago but I'm pretty sure I created a brand new `conda` environment and reinstalled everything I needed in it, and everything worked as expected.
