### ISSUE TITLE
pandas-profiling not installable with Python 3.6

### ISSUE THREAD

**Issue by dspyrhsu** [JosPolfliet/pandas-profiling#50]
When trying to install pandas-profiling with a current Anaconda version, I get an error. This is because I am already on Python 3.6 and conda info shows:
`
conda info pandas-profiling=1.3.0
Fetching package metadata .............

pandas-profiling 1.3.0 py27_0
-----------------------------
file name   : pandas-profiling-1.3.0-py27_0.tar.bz2
name        : pandas-profiling
version     : 1.3.0
build string: py27_0
build number: 0
channel     : conda-forge
size        : 28 KB
arch        : x86_64
has_prefix  : False
license     : MIT
md5         : a7a2a6ef13981cfb2224fd788059a3fa
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pandas-profiling-1.3.0-py27_0.tar.bz2
dependencies:
    jinja2 >=2.8
    matplotlib >=1.4
    pandas >=0.16
    python 2.7*
    six >=1.9

pandas-profiling 1.3.0 py34_0
-----------------------------
file name   : pandas-profiling-1.3.0-py34_0.tar.bz2
name        : pandas-profiling
version     : 1.3.0
build string: py34_0
build number: 0
channel     : conda-forge
size        : 28 KB
arch        : x86_64
has_prefix  : False
license     : MIT
md5         : 2a2116f78d6be8513c014a7b9dec6720
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pandas-profiling-1.3.0-py34_0.tar.bz2
dependencies:
    jinja2 >=2.8
    matplotlib >=1.4
    pandas >=0.16
    python 3.4*
    six >=1.9

pandas-profiling 1.3.0 py35_0
-----------------------------
file name   : pandas-profiling-1.3.0-py35_0.tar.bz2
name        : pandas-profiling
version     : 1.3.0
build string: py35_0
build number: 0
channel     : conda-forge
size        : 223 KB
arch        : x86_64
has_prefix  : False
license     : MIT
md5         : a00d9fab0150a53d8c6c234bf9cb5d22
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pandas-profiling-1.3.0-py35_0.tar.bz2
dependencies:
    jinja2 >=2.8
    matplotlib >=1.4
    pandas >=0.16
    python 3.5*
    six >=1.9
`
Could you please provide a version for 3.6? Thanks!

**Comment by dspyrhsu** [comment]
Ok, checked again today and pandas profiling is now available in version 1.4.0 and also for Python 3.6 -> issue can be closed!

**Comment by NithyaGrace** [comment]
I am unable to import pandas profiling
![screen shot 2018-03-16 at 11 36 52 am](https://user-images.githubusercontent.com/34020307/37506241-efb0fad4-290e-11e8-8b20-dd4f1c1468a4.png)

**Comment by harrywinks** [comment]
I am in same problem...

**Comment by marcel-goldschen-ohm** [comment]
Same problem years later. Any solutions?

**Comment by sbrugman** [comment]
Hi @marcel-goldschen-ohm, py.36 is supported and  should work out of the box. Could you try reinstalling and see if the issue persists? Occasionally in a notebook, it requires installing it in the same  environment like this:
```
import sys
!{sys.executable} -m pip install pandas-profiling
```
(kernel restart needed)

**Comment by marcel-goldschen-ohm** [comment]
`pip install pandas-profiling` worked. For whatever reason, the conda version is messed up.
