### ISSUE TITLE
Incorrect calculation for % unique for variables with missing values

### ISSUE THREAD

**Issue by mhowison** [JosPolfliet/pandas-profiling#56]
We've found that the % unique calculation sometimes shows up as >100%, and the it appears to be in cases where there are a small number of unique values and "missing" is one of them. It looks like that "missing" is counted in the numerator but not in the denominator of the calculation.

For example, we have a variable with 2 possible values ("Y" and "missing") that shows 200.0% unique (e.g. 2/1).

Another variable with 3 possible values ("Y", "N", "missing") shows 150.0% unique (e.g. 3/2).

**Comment by romainx** [comment]
The current implementation includes `na` in distinct count. But when the percentage of unique values is computed the distinct count is divided by the count that does not include na. This is the cause of the inconsistent behavior highlighted here.

I've fixed the implementation to be consistent: now `na` is considered as a distinct value also in the percentage of unique values and the result is consistent.

```Python
df = pd.DataFrame({'test':[0, 1, np.nan]})
pandas_profiling.ProfileReport(df)
# Unique (%)	100.0%
# Instead of previously
# Unique (%)	150.0%
```
