### ISSUE TITLE
After pandas update: module 'pandas' has no attribute 'api' 

### ISSUE THREAD

**Issue by eamag** [JosPolfliet/pandas-profiling#58]
When
 ```
from pandas_profiling import ProfileReport 
ProfileReport(df)
```
I get
`Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/base.py", line 247, in multiprocess_func
    return x[0], describe_1d(x[1], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/base.py", line 232, in describe_1d
    vartype = get_vartype(data)
  File "/usr/local/lib/python3.5/dist-packages/pandas_profiling/base.py", line 46, in get_vartype
    elif pd.api.types.is_numeric_dtype(data):
AttributeError: module 'pandas' has no attribute 'api'
"""`
pandas-0.20.3
pandas_profiling is from pypl

**Comment by gsoul** [comment]
See same error

**Comment by 911gt5** [comment]
Same error

**Comment by JosPolfliet** [comment]
Thanks for reporting all, I have foreseen time this weekend to look what's wrong. Looks like pandas deprecated a function we were using so I think it will be a quick fix.

**Comment by JosPolfliet** [comment]
I can't recreate this on python3.5 with pandas-0.20.3 on MacOS... Also: the [pandas.api.types.is_numeric_dtype](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.api.types.is_numeric_dtype.html ) still exists. 

Can any of you please run
`
import pandas as pd
pd.api.types.is_numeric_dtype(float)
`
which should just return 'True'. If this gives an error, there might be something fishy going on with the imports of pandas.

**Comment by eamag** [comment]
Yes, it returns True, have no error now ¯\_(ツ)_/¯
