### ISSUE TITLE
Passing `check_correlation` kwarg to ProfileReport fails

### ISSUE THREAD

**Issue by Aylr** [JosPolfliet/pandas-profiling#62]
I have run across uses for this where correlation isn't useful. In trying to disable it, the histogram function fails when the kwarg is given.

## STR

1. load/create a dataframe
2. profile `pandas_profiling.ProfileReport(data, check_correlation=False)`

## Stacktrace

TypeError                                 Traceback (most recent call last)
<ipython-input-6-bd3fffaaf3d6> in <module>()
----> 1 pandas_profiling.ProfileReport(data, check_correlation=False)

/Users/taylor.miller/anaconda/lib/python3.6/site-packages/pandas_profiling/__init__.py in __init__(self, df, **kwargs)
     15         sample = kwargs.get('sample', df.head())
     16 
---> 17         description_set = describe(df, **kwargs)
     18 
     19         self.html = to_html(sample,

/Users/taylor.miller/anaconda/lib/python3.6/site-packages/pandas_profiling/base.py in describe(df, bins, correlation_overrides, pool_size, **kwargs)
    282     pool = multiprocessing.Pool(pool_size)
    283     local_multiprocess_func = partial(multiprocess_func, **kwargs)
--> 284     ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}
    285     pool.close()
    286 

/Users/taylor.miller/anaconda/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    258         in a list that is returned.
    259         '''
--> 260         return self._map_async(func, iterable, mapstar, chunksize).get()
    261 
    262     def starmap(self, func, iterable, chunksize=None):

/Users/taylor.miller/anaconda/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    606             return self._value
    607         else:
--> 608             raise self._value
    609 
    610     def _set(self, i, obj):

TypeError: _plot_histogram() got an unexpected keyword argument 'check_correlation'

**Comment by romainx** [comment]
Hello, 

The ability to disable the check correlation has been added with the implementation of the issue #43 which is not part of the latest version of pandas-profiling (1.4) available in PyPI. It has been implemented after and will be available, I guess, in the next version. In the meantime, if you really need it, you can download the current version from github and use it for example by adding it to your `PYTHONPATH`.

```bash
#!/bin/sh

PROF_DIR="$HOME/Git/pandas-profiling/"
export PYTHONPATH="$PYTHONPATH:$PROF_DIR"
jupyter notebook
```
Best,
Romain

**Comment by Aylr** [comment]
Awesome! Thanks! (It's hard to overstate how helpful analyst in my org are finding this package!)

**Comment by romainx** [comment]
Hello,

Good to hear this feedback.
Thank you.

**Comment by DyegoDS** [comment]
> Hello,
> 
> The ability to disable the check correlation has been added with the implementation of the issue #43 which is not part of the latest version of pandas-profiling (1.4) available in PyPI. It has been implemented after and will be available, I guess, in the next version. In the meantime, if you really need it, you can download the current version from github and use it for example by adding it to your `PYTHONPATH`.
> 
> ```shell
> #!/bin/sh
> 
> PROF_DIR="$HOME/Git/pandas-profiling/"
> export PYTHONPATH="$PYTHONPATH:$PROF_DIR"
> jupyter notebook
> ```
> 
> Best,
> Romain

Thank you!

It helps me...
