### ISSUE TITLE
Warnings column names should be links to details in Variables section

### ISSUE THREAD

**Issue by Aylr** [JosPolfliet/pandas-profiling#66]
## Benefits

- This would expedite navigation through large reports.
- I've seen a few click them with expectation of this behavior, so it seems natural.

Will submit a PR if you agree @JosPolfliet

**Comment by romainx** [comment]
Hello,

If you have the time we will be happy to integrate this improvement in the new version.

Thanks !

**Comment by conradoqg** [comment]
Hey,

With the above PR #82 merged, every variable name has a link for its respective analysis.

I think we can close this issue after those changes.

Best

**Comment by romainx** [comment]
Hello, 

I confirm it's implemented now and very useful.

Thanks to all.
