### ISSUE TITLE
ProfileReport fails if dataframe contains boolean columns

### ISSUE THREAD

**Issue by Aylr** [JosPolfliet/pandas-profiling#77]
Despite #25 and #64  , this appears to still be an issue.

## Steps to reproduce

```
foo = pd.DataFrame({
    'a': [1, 2, 3],
    'bool': [True, False, True],
})

# fails
pandas_profiling.ProfileReport(foo)

# succeeds (convert to integer)
foo['bool'] = np.where(foo['bool'], 1, 0)
pandas_profiling.ProfileReport(foo)
```

Does anyone have any suggestions before I submit a PR?

**Comment by conradoqg** [comment]
I wasn't able to reproduce this problem with the latest commit.

Could you give more details about your environment?

My:
```
CPython 3.6.0
IPython 6.2.1

pandas 0.19.2
numpy 1.13.3
matplotlib 2.1.0
six 1.11.0

compiler   : MSC v.1900 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
CPU cores  : 8
interpreter: 64bit
Git hash   : bc52a3cc10863c54c592210e86989d3ef733f138
```

Best

**Comment by romainx** [comment]
I confirm, I'm not able to reproduce the problem in my environment.
Could you also share the error observed?

Thanks

**Comment by Aylr** [comment]
I was not able to reproduce this! When I was certain I could it turned out ipython must have been caching a non-master branch of the library.

From (another) clean environment I was able to get both code snippets above to work.

Sorry about the user error!!

**Comment by Aylr** [comment]
Since it's been almost a year since the last release when can we expect a new one on pypi? :smile:

**Comment by conradoqg** [comment]
Hey,

I think a new release is a good idea but before that, this month I hope to be able to do a series of new features and bug fixes.

If the authors can wait a week, I think the most important ones will be ready.

Best

**Comment by romainx** [comment]
Hello,

I'm not the author, but I agree. I think new features are mandatory before delivering a new version and I will help improving it. On my side I would be happy to improve testing and CI. 

We have to check with @JosPolfliet his target date. In my point of view we should commit to issue a new version before the end of the first quarter 😄.

**Comment by conradoqg** [comment]
Hey,

I'm confident that after the PR #82 we don't have any more problems with bool variables.

@romainx Can you open a specific issue to release a new version (maybe we can create a list of desired improvements/issues to be fixed).

I think we can close this issue after those changes.

Best

**Comment by romainx** [comment]
Hello,

I've created a new one (#86) to publish a new release.
